feat(09-functions): add print PR data

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -7,6 +7,23 @@ jobs:
     echo1:
         runs-on: ubuntu-latest
         steps:
+            - name: Print PR title
+              run: |
+                echo "PR title: ${{ github.event.pull_request.title }}"
+            - name: Print PR labels
+              run: |          
+                cat << EOF   
+                echo "PR labels: ${{ tojson(github.event.pull_request.labels) }}"
+                EOF
+            - name: Bug Step
+              if: ${{!cancelled() && contains(github.event.pull_request.title, 'fix')}}
+              run: echo "I am a bug fix"
+            - name: Sleep 30 seconds
+              run: sleep 30
+            - name: Failing Step
+              run: |
+                echo "This step will fail"
+                exit 1
             - name: Failing Step
               run: |
                 sleep 30
